### ISSUE TITLE
Configuration error!

### ISSUE THREAD

**Issue by adamjakab** [adamjakab/BeetsPluginGoingRunning#2]
Error message: `configuration error: goingrunning.trainings.walking.target not found`

```yaml
goingrunning:
  song_bpm: [111, 222]
  song_len: [120, 240]
  duration: 120
  target: SONY
  targets:
    TEST: ~/Music/tmp/
    SONY: /Volumes/WALKMAN/MUSIC/AUTO/
  clean_target: true
  trainings:
    test:
      alias: "Born to run"
      song_bpm: [90, 150]
      song_len: [120, 300]
      duration: 180
      target: TEST
    walking:
      alias: "Born to run"
      song_bpm: [0, 130]
      song_len: [0, 600]
      duration: 180
    longrun:
      alias: "Born to run"
      song_bpm: [120, 150]
      song_len: [120, 300]
      duration: 180
```
beets version 1.4.9
Python version 3.7.6
plugins: convert, duplicates, fromfilename, goingrunning, info, inline, the, zero

```
goingrunning -l
Available trainings:
======================================== ::: test
alias: Born to run
duration: 180
song_bpm: [90, 150]
song_len: [120, 300]
target: TEST
======================================== ::: walking
alias: Born to run
duration: 180
song_bpm: [0, 130]
song_len: [0, 600]
target: SONY
======================================== ::: longrun
alias: Born to run
duration: 180
song_bpm: [120, 150]
song_len: [120, 300]
target: SONY
```
So configuration is correctly read

If I put the target directly on the training leaf it works.
