### ISSUE TITLE
fallback configuration is not picked up for ordering

### ISSUE THREAD

**Issue by adamjakab** [adamjakab/BeetsPluginGoingRunning#22]
when using this configuration:

```yaml
trainings:
        fallback:
            target: TEST
            increment_play_count: yes
            favour_unplayed: yes
            ordering:
                original_year: 25
                bpm: 50
                mood_aggressive: 50
                danceable: 100
                mood_relaxed: -100
        longrun-la:
            use_flavours: [running, intensity_low, genre_alternative]
            duration: 150
            target: SONY
```

and executing `beet -vv run longrun-la`

the plugin reports: 

```bash
user configuration: /Users/jackisback/.config/beets/config.yaml
data directory: /Users/jackisback/.config/beets
plugin paths: /Users/jackisback/Documents/Projects/Python/BeetsPluginGenreFixer/beetsplug
Sending event: pluginload
inline: adding item field initial_letter
inline: adding item field disc_num_prefix
library database: /Users/jackisback/.config/beets/real_library.db
library directory: /Volumes/J/Music
Sending event: library_opened
goingrunning: Handling training: longrun-la
goingrunning: Getting attribute[device_root] for target: SONY
goingrunning: Finding target: SONY
goingrunning: Found target[SONY] attribute[device_root] path: /Volumes/WALKMAN
goingrunning: Getting attribute[device_path] for target: SONY
goingrunning: Finding target: SONY
goingrunning: Found target[SONY] attribute[device_path] path: MUSIC/AUTO
goingrunning: Found target[SONY] path: SONY
goingrunning: Command query elements: []
goingrunning: Training query elements: []
goingrunning: Flavour query elements: ["^genre:Experimental", "^genre:Christian", "^genre:Christmas", "^genre:Speech", "bpm:..110", "mood_aggressive:..0.1", "genre:Alternative Rock", "genre:Grunge", "genre:Indie", "genre:New Wave", "genre:Progressive", "genre:Psychedelic Rock", "genre:Punk", "genre:Ska"]
goingrunning: Combined query elements: ["^genre:Experimental", "^genre:Christian", "^genre:Christmas", "^genre:Speech", "bpm:..110", "mood_aggressive:..0.1", "genre:Alternative Rock", "genre:Grunge", "genre:Indie", "genre:New Wave", "genre:Progressive", "genre:Psychedelic Rock", "genre:Punk", "genre:Ska"]
goingrunning: ^genre: AndQuery([NotQuery(SubstringQuery("genre", "Experimental", True)), NotQuery(SubstringQuery("genre", "Christian", True)), NotQuery(SubstringQuery("genre", "Christmas", True)), NotQuery(SubstringQuery("genre", "Speech", True))])
goingrunning: bpm: NumericQuery("bpm", "..110", True)
goingrunning: mood_aggressive: NumericQuery("mood_aggressive", "..0.1", False)
goingrunning: genre: OrQuery([SubstringQuery("genre", "Alternative Rock", True), SubstringQuery("genre", "Grunge", True), SubstringQuery("genre", "Indie", True), SubstringQuery("genre", "New Wave", True), SubstringQuery("genre", "Progressive", True), SubstringQuery("genre", "Psychedelic Rock", True), SubstringQuery("genre", "Punk", True), SubstringQuery("genre", "Ska", True)])
goingrunning: Parsed query: AndQuery([AndQuery([NotQuery(SubstringQuery("genre", "Experimental", True)), NotQuery(SubstringQuery("genre", "Christian", True)), NotQuery(SubstringQuery("genre", "Christmas", True)), NotQuery(SubstringQuery("genre", "Speech", True))]), NumericQuery("bpm", "..110", True), NumericQuery("mood_aggressive", "..0.1", False), OrQuery([SubstringQuery("genre", "Alternative Rock", True), SubstringQuery("genre", "Grunge", True), SubstringQuery("genre", "Indie", True), SubstringQuery("genre", "New Wave", True), SubstringQuery("genre", "Progressive", True), SubstringQuery("genre", "Psychedelic Rock", True), SubstringQuery("genre", "Punk", True), SubstringQuery("genre", "Ska", True)])])
goingrunning: ORDERING permutation: ScoreBasedLinearPermutation
goingrunning: Scoring 753 items...
goingrunning: ORDER INFO: {}
goingrunning: PICKER strategy: RandomFromBinsPicker ("favour_unplayed": yes)
```

so the ordering key is not picked up from the fallback training. (It howvever seems that the `favour_unplayed` is picked up).

`GoingRunning(beets-goingrunning) plugin for Beets: v1.2.1`
